const scenarios={
 data:{title:'Gift data in seconds',copy:'A contextual suggestion turns a chat message into a secure MTN transaction.',incoming:'Hi! Please can you send me 2GB? My data just finished 🙏',suggest:'Gift 2GB',note:'Suggested from your message · processed on device',icon:'gift',heading:'Gift data',sub:'Review the details before you continue.',amount:'2 GB',recipient:'Ada · 0803 987 6543',source:'Main data balance',success:'2GB sent to Ada',receipt:'Data gift'},
 money:{title:'Pay within the conversation',copy:'MoMo appears at the moment payment intent is expressed, with a secure confirmation flow.',incoming:'The tickets are ₦5,000. Can you send it now?',suggest:'Send ₦5,000',note:'MoMo suggestion · amount detected on device',icon:'wallet',heading:'Send with MoMo',sub:'Confirm this MoMo transfer.',amount:'₦5,000',recipient:'Ada · 0803 987 6543',source:'MoMo wallet · ₦24,800',success:'₦5,000 sent to Ada',receipt:'MoMo transfer'},
 airtime:{title:'Top up without switching apps',copy:'Common purchases stay one tap away, even when no contextual prompt is needed.',incoming:'Please call me when you can. I need to tell you something.',suggest:'Buy ₦1,000',note:'Quick action · choose an amount to continue',icon:'signal',heading:'Buy airtime',sub:'Top up your connected MTN line.',amount:'₦1,000',recipient:'My line · 0803 123 4567',source:'Bank card · •••• 3048',success:'₦1,000 airtime purchased',receipt:'Airtime purchase'},
 ask:{title:'Ask MTN in natural language',copy:'Customers can discover the right bundle using a conversational assistant built into the keyboard.',incoming:'You will need plenty of data for the trip this month.',suggest:'Ask about plans',note:'Ask MTN · account-aware answers',icon:'spark',heading:'Ask MTN',sub:'A recommendation based on your simulated usage.',amount:'25GB Monthly',recipient:'Best fit for your usage',source:'₦6,500 · 30 days',success:'25GB plan selected',receipt:'Bundle selection'}
};
let current='data',stage=0,currentApp='whatsapp';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const letters=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];
$('#keys').innerHTML=letters.map(r=>`<div class="key-row">${[...r].map(k=>`<button class="key">${k}</button>`).join('')}</div>`).join('');
function setStage(n){stage=n;$$('#steps li').forEach((li,i)=>{li.classList.toggle('active',i===Math.min(n,4));li.classList.toggle('done',i<n)});}
function selectScenario(key){current=key;const s=scenarios[key];setStage(0);$('#journeyTitle').textContent=s.title;$('#journeyCopy').textContent=s.copy;$('#incomingBubble').innerHTML=`${s.incoming}<small>9:38</small>`;$('#suggestionText').textContent=s.note;$$('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.scenario===key));$$('.action-chip').forEach(b=>b.classList.remove('primary'));const target=$(`.action-chip[data-action="${key}"]`);if(target){target.classList.add('primary');target.innerHTML=`<svg><use href="#${s.icon}"/></svg>${s.suggest}`}closeSheet();}
function reviewTemplate(){const s=scenarios[current];return `<div class="sheet-icon"><svg><use href="#${s.icon}"/></svg></div><h2>${s.heading}</h2><p class="sub">${s.sub}</p><div class="review-card"><div class="review-row"><span>${current==='ask'?'Recommended plan':'Recipient'}</span><b>${s.recipient}</b></div><div class="review-row"><span>${current==='data'?'Data amount':'Amount'}</span><b>${s.amount}</b></div><div class="review-row"><span>${current==='ask'?'Price & validity':'Pay from'}</span><b>${s.source}</b></div></div><button class="yellow-btn" id="continueBtn">${current==='ask'?'Choose this plan':'Continue securely'}</button><p class="fineprint">This is a simulated transaction. No charge will be made.</p>`}
function openAction(){if(current==='ask'){openAsk();return}$('#transactionSheet').classList.remove('compact-assistant');setStage(2);$('#sheetContent').innerHTML=reviewTemplate();openSheet();$('#continueBtn').onclick=showPin;}
function openSheet(){$('#backdrop').classList.add('show');$('#transactionSheet').classList.add('show')}
function openAsk(){$('#transactionSheet').classList.add('compact-assistant');setStage(2);$('#sheetContent').innerHTML=`<div class="ask-mini-head"><span class="sheet-icon"><svg><use href="#spark"/></svg></span><div><h2>Ask MTN</h2><p class="sub">Quick answers without leaving the app</p></div></div><div class="ask-options"><button class="ask-option" data-answer="balance">My balance</button><button class="ask-option" data-answer="last">Will it last?</button><button class="ask-option" data-answer="plan">Best bundle</button></div><div id="assistantAnswer"></div><div class="ask-input-row"><input id="askInput" placeholder="Ask MTN anything…"><button id="askSend" aria-label="Send">↑</button></div>`;openSheet();$$('.ask-option').forEach(b=>b.onclick=()=>answerAsk(b.dataset.answer));$('#askSend').onclick=()=>answerAsk('custom');$('#askInput').addEventListener('keydown',e=>{if(e.key==='Enter')answerAsk('custom')});}
function answerAsk(type){const answers={balance:'You have <b>12.8GB</b> remaining from your 20GB monthly bundle. It expires in 12 days.',last:'At your current average of 1.2GB per day, your data will likely last <b>9 more days</b>. That is about 3 days before expiry.',plan:'Based on your recent usage, the <b>25GB Monthly Plan</b> is your best fit. It gives you enough headroom without excessive unused data.',custom:'I can help with your balance, usage forecast and bundle recommendations. Try asking: <b>“Will my data last?”</b>'};$('#assistantAnswer').innerHTML=`<div class="assistant-answer"><b>MTN Assistant</b>${answers[type]}</div>`;setStage(3)}
function openUsage(){$('#transactionSheet').classList.remove('compact-assistant');setStage(2);$('#sheetContent').innerHTML=`<div class="sheet-icon"><svg><use href="#signal"/></svg></div><h2>Your data at a glance</h2><p class="sub">Live-style insights based on simulated usage.</p><div class="usage-grid"><div><small>REMAINING</small><b>12.8GB</b></div><div><small>DAYS LEFT</small><b>12 days</b></div><div><small>USED TODAY</small><b>1.2GB</b></div><div><small>DAILY AVERAGE</small><b>1.1GB</b></div></div><div class="usage-metric"><div class="usage-metric-head"><span>Bundle used</span><b>36%</b></div><div class="usage-bar"><i style="width:36%"></i></div></div><div class="usage-insight"><b>Data Guardian insight:</b> At your current rate, your data is likely to last 9 days. Reduce video quality to help it reach the expiry date.</div><button class="yellow-btn" id="usageDone">Got it</button>`;openSheet();$('#usageDone').onclick=closeSheet;}
function showPin(){const s=scenarios[current];setStage(3);$('#sheetContent').innerHTML=`<div class="sheet-icon"><svg><use href="#lock"/></svg></div><h2>Confirm with MTN PIN</h2><p class="sub">Enter any four digits to approve ${current==='money'?'this MoMo transfer':'this action'}.</p><div class="pin-inputs">${[0,1,2,3].map(i=>`<input inputmode="numeric" maxlength="1" aria-label="PIN digit ${i+1}">`).join('')}</div><button class="dark-btn" id="confirmBtn" disabled>Confirm ${s.amount}</button><p class="fineprint">Your PIN is encrypted and never accessible to the keyboard.</p>`;const inputs=$$('.pin-inputs input'),btn=$('#confirmBtn');inputs.forEach((inp,i)=>inp.addEventListener('input',()=>{inp.value=inp.value.replace(/\D/g,'');if(inp.value&&inputs[i+1])inputs[i+1].focus();btn.disabled=!inputs.every(x=>x.value)}));inputs[0].focus();btn.onclick=showSuccess;}
function showSuccess(){const s=scenarios[current];setStage(4);$('#sheetContent').innerHTML=`<div class="success-state"><div class="success-check"><svg><use href="#check"/></svg></div><h2>All done</h2><p class="amount">${s.amount}</p><p class="sub">${s.success}</p><div class="receipt"><div class="review-row"><span>Transaction</span><b>${s.receipt}</b></div><div class="review-row"><span>Reference</span><b>MTN·${Math.floor(100000+Math.random()*899999)}</b></div><div class="review-row"><span>Status</span><b style="color:#16866b">Successful</b></div></div><button class="yellow-btn" id="doneBtn">Return to chat</button></div>`;$('#doneBtn').onclick=finish;}
function finish(){const s=scenarios[current];closeSheet();$('#toast span').textContent=s.success;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600);const bubble=document.createElement('div');bubble.className='bubble outgoing';bubble.innerHTML=`${s.success} ✓<small>9:41 ✓✓</small>`;$('#chatArea').insertBefore(bubble,$('.typing-line'));}
function closeSheet(){$('#backdrop').classList.remove('show');$('#transactionSheet').classList.remove('show')}
$$('.scenario').forEach(b=>b.onclick=()=>{selectScenario(b.dataset.scenario);if(b.dataset.scenario==='ask')setTimeout(openAsk,180)});$$('.action-chip').forEach(b=>b.onclick=()=>{if(b.dataset.action!==current)selectScenario(b.dataset.action);setStage(1);setTimeout(openAction,180)});$('#askKey').onclick=()=>{current='ask';$$('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.scenario==='ask'));setStage(1);openAsk()};$('#sheetClose').onclick=closeSheet;$('#backdrop').onclick=closeSheet;$('#restartBtn').onclick=()=>location.reload();$('#usageStrip').onclick=openUsage;
function switchApp(app){currentApp=app;const phone=$('.phone');phone.classList.remove('instagram','messages');if(app!=='whatsapp')phone.classList.add(app);$$('.app-choice').forEach(b=>b.classList.toggle('active',b.dataset.app===app));const labels={whatsapp:'online',instagram:'Active now',messages:'iMessage'};$('#appStatus').textContent=labels[app]}
$$('.app-choice').forEach(b=>b.onclick=()=>switchApp(b.dataset.app));
function openPrivacy(){$('#privacyModal').classList.add('show');$('#modalBackdrop').classList.add('show')};function closePrivacy(){$('#privacyModal').classList.remove('show');$('#modalBackdrop').classList.remove('show')};$('#privacyBtn').onclick=openPrivacy;$('#privacyClose').onclick=closePrivacy;$('#modalBackdrop').onclick=closePrivacy;$('#savePrivacy').onclick=()=>{closePrivacy();$('#toast span').textContent='Privacy preferences saved';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)};
selectScenario('data');
